general:
  seed: 3
  device: 0

source_dataset:
  name: cifar10

neuron_dataset:
  bs: 4
  num_workers: 4
  val_ratio: 0.5

model:
  symmetry: "I"
  num_layers: 3
  dim_embed: 48
  residual: True
  dim_output: 1
  task: "gap_minimization"

training:
  lr: 0.001
  task: "regression"
  optim: "adam"
  wd: 0
  epochs: 100
  sched:
    type: "steplr"
    step_size: 10
    gamma: 0.5


wandb:
  project_name: TESTT