general:
  seed: 3
  device: 0

source_dataset:
  name: cifar10

neuron_dataset:
  bs: 8
  num_workers: 4
  val_ratio: 0.5

model:
  symmetry: "set"
  num_layers: 3
  dim_embed: 24
  residual: True
  pooling: "mean" # TODO: need to actually make effective
  task: "certainty"
  dim_output: 1

training:
  lr: 0.001
  task: "classification"
  optim: "adam"
  sched:
    type: "steplr"
    step_size: 25
    gamma: 0.5
  
  wd: 0 
  epochs: 50

wandb:
  project_name: TESTT